version: "3.7"

services:
  app:
    build: ./app
    command: sh -c "python manage.py migrate && gunicorn config.wsgi:application -w 2 -b :8000"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - .env:/app/.env
    depends_on:
      - rabbitmq
    env_file:
      - .env
    networks:
      - mqtt
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - mqtt
  equipamento:
    build: ./equipamento/
    command:
      - ./equipamento
    volumes:
      - ./equipamento:/app
    networks:
      - mqtt
    env_file:
      - .env
    environment:
      - MQTT_ADDRESS=mosquitto
      - MQTT_USERNAME=teste
      - MQTT_PASSWORD=teste
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - mqtt
    env_file:
      - .env
  celery:
    build: ./app
    command: "python -m celery -A config worker -l info --loglevel=info"
    volumes:
      - ./app:/app
      - .env:/app/.env
    depends_on:
      - rabbitmq
    env_file:
      - .env
    networks:
      - mqtt

volumes:
  rabbitmq_data:

networks:
  mqtt: