# Generated by Django 5.0.3 on 2024-03-26 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='hardware.station'),
            preserve_default=False,
        ),
    ]
